baseURL = 'https://optionsmaddy.github.io/'
languageCode = 'en-us'
title = 'OptionsMaddy'

[params]
title = "OptionsMaddy"
author = "Maddy"
description = """ âš–ï¸ Trading Options ðŸ¤¹
Motto : Consistency, Patience & Discipline.
"""
#displayMode = "light"
profilePicture = "images/logo2.png"
mainSections = ["posts"]
#fullPostContent = true
keywords = "trading-options"
favicon = "favicon/favicon.ico"

doNotLoadAnimations = false
reversepagetitle = true 
enableMediumZoom = true
contentratio = 0.75
#hidesidebar = true
singleDateFormat = "Mon, Jan 2, 2006"
indexDateFormat = "Mon, Jan 2, 2006"
listDateFormat = "Jan 2"
readMore = true
disqusShortname = "optionsmaddy"

contactFormAction = "https://formspree.io/f/xyyabgnb"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://www.twitter.com/optionsmaddy"

[[params.socialIcons]]
icon = "fab fa-youtube"
title = "twitter"
url = "https://www.youtube.com/@optionsmaddy"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "Email"
url = "mailto:optionsmaddy@gmail.com"

#[[params.socialIcons]]
#con = "fas fa-check-to-slot"
#title = "sensibull"
#url = "https://web.sensibull.com/verified-pnl/oldfashioned-lime"

[[params.socialIcons]]
#icon = "fa-solid fa-envelope-open-text"
icon = "fa-solid fa-bell"
title = "Substack"
url = "https://substack.com/"

summarylength = 300
enableEmoji = true
enableRobotsTXT = true

localizedDates = true

relatedPosts = true
numberOfRelatedPosts = 3

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80



[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Tags"
  weight = 300
  identifier = "tags"
  url = "/tags/"


  #[[menu.main]]
  #name = "ðŸ—‚ï¸Categories"
  #weight = 320
  #identifier = "categories"
  #url = "/categories/"
  #parent = "find"


  #[[menu.main]]
  #name = "ðŸ’¥Portfolio"
  #weight = 400
  #identifier = "portfolio"
  #url = "/portfolio/"

  [[menu.main]]
  name = "About"
  weight = 500
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/contact/"

  [module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false