baseURL = 'https://optionsmaddy.github.io/'
languageCode = 'en-us'
title = 'OptionsMaddy'

#disqusShortname = 'optionsmaddy'
googleFonts = ["Readex+Pro"]

[params.utterances]
repo = "optionsmaddy/optionsmaddy.github.io"
issueTerm = "pathname"
theme= "github-dark"
label = "maddyoptions-comment"

[params]
title = "OptionsMaddy"
author = "Maddy"
description = """ âš–ï¸ Trading Options ðŸ¤¹
Motto : Consistency, Patience & Discipline.
Here, I Share My Trading NotesðŸ“”.
"""
profilePicture = "images/logodark.png"
mainSections = ["post"]

gtagId = "G-4B0KQ8RWDQ"
enableRobotsTXT = true
keywords = "trading-options"
favicon = "favicon/favicon.ico"
doNotLoadAnimations = false
reversepagetitle = true 
enableMediumZoom = true
contentratio = 0.75
singleDateFormat = "Mon, Jan 2, 2006"
indexDateFormat = "Mon, Jan 2, 2006"
listDateFormat = "Jan 2"
readMore = true
summarylength = 300
enableEmoji = true
localizedDates = true
relatedPosts = false
numberOfRelatedPosts = 3
contactFormReCaptcha = "6Lc-VoUlAAAAAH9oCf5GGtKsICLjyucEJmY-biNP"
contactFormAction = "https://formspree.io/f/xyyabgnb"

#fullPostContent = true
#hidesidebar = true
displayMode = "dark"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://www.twitter.com/optionsmaddy"

[[params.socialIcons]]
icon = "fab fa-youtube"
title = "twitter"
url = "https://www.youtube.com/@optionsmaddy"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "Email"
url = "mailto:optionsmaddy@gmail.com"

[[params.socialIcons]]
#icon = "fa-solid fa-envelope-open-text"
icon = "fa-solid fa-bell"
title = "Substack"
url = "https://substack.com/optionsmaddy"

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80



[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Post"
  weight = 200
  identifier = "post"
  url = "/post/"

  [[menu.main]]
  name = "Tags"
  weight = 300
  identifier = "tags"
  url = "/tags/"


  #[[menu.main]]
  #name = "ðŸ—‚ï¸Categories"
  #weight = 320
  #identifier = "categories"
  #url = "/categories/"
  #parent = "find"

  #[[menu.main]]
  #name = "ðŸ’¥Portfolio"
  #weight = 400
  #identifier = "portfolio"
  #url = "/portfolio/"

  [[menu.main]]
  name = "About"
  weight = 500
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/contact/"

  [module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false

